/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concesionaria;

import concesionaria.customImplementations.ConcesionariaSelectionListener;
import concesionaria.customImplementations.VehiculosTableModel;
import concesionaria.dominio.Auto;
import concesionaria.dominio.Moto;
import concesionaria.dominio.Vehiculo;
import concesionaria.repositorios.VehiculoRepositorio;
import concesionaria.servicios.VehiculosService;
import concesionaria.views.EdicionVehiculosPanel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * Vista principal de la aplicacion
 * 
 * @author joni
 */
public class Concesionaria extends javax.swing.JFrame {

    //private Boolean isEditOpen = false; 
    
     private JFrame frameEdit = new JFrame();
     private EdicionVehiculosPanel previoEdicionVehiculosPanel;
     private ConcesionariaSelectionListener concesionariaSelectionListener;
    
    /**
     * Creates new form Listado
     */
    public Concesionaria() {
        initComponents();
        
        vehiculosTable.setRowSelectionAllowed(false);
        this.loadTable();
        
        
    }

    /**
     * Carga la tabla de vehiculos
     */
    public void loadTable(){
       
      DefaultTableModel dm = (DefaultTableModel)vehiculosTable.getModel();
        dm.getDataVector().removeAllElements();
        
        if (this.concesionariaSelectionListener != null) 
            vehiculosTable.getSelectionModel().removeListSelectionListener(this.concesionariaSelectionListener);
            
        
        dm.fireTableDataChanged(); // notifies the JTable that the model has changed
        
        VehiculosService vehiculoService = new VehiculosService();
        
        // PARA PROBAR EL SAVE
        //Vehiculo ve = new Moto();
        //ve.setTipo(1);
        //ve.setColor("Azul");
        //VehiculoRepositorio repo = new VehiculoRepositorio();
        //repo.listar(ve);
        //System.out.println()
        try{
            List<Vehiculo> vehiculos = vehiculoService.getAll();

            String[] columnNames = {
                "Id",
                "Marca",
                "Modelo",
                "Año",
                "Kilometros",
                "Precio",
                "Comisión",
                "Impuesto"
            };

            VehiculosTableModel tableModel = new VehiculosTableModel(columnNames, 0);
            vehiculosTable.setModel(tableModel);

            for (Vehiculo vehiculo : vehiculos) {
                Object[] vehiculosData = new Object[] {
                    vehiculo.getId(),
                    vehiculo.getMarca(), 
                    vehiculo.getModelo(), 
                    vehiculo.getAnio(), 
                    vehiculo.getCantidadKilometros(), 
                    vehiculo.getPrecio(), 
                    vehiculo.calcularComisionVendedor(),
                    vehiculo.calcularImpuesto()
                };

                tableModel.addRow(vehiculosData);
            }   
            
            this.concesionariaSelectionListener = new ConcesionariaSelectionListener(this);
            vehiculosTable.getSelectionModel().addListSelectionListener(this.concesionariaSelectionListener);
        }
        catch(Exception e){
            int a = 0;
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vehiculosTable = new javax.swing.JTable();
        panel3 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        button3 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vehiculosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(vehiculosTable);

        panel3.setBackground(new java.awt.Color(21, 77, 161));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Concesionaria Buenos Aires");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        button3.setActionCommand("CREAR");
        button3.setBackground(new java.awt.Color(52, 152, 219));
        button3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setLabel("CREAR");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento del boton CREAR
     * 
     * @param evt 
     */
    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed

         JFrame f=new JFrame();
         
        EdicionVehiculosPanel edicionVehiculosPanel = new EdicionVehiculosPanel(f, this);

         f.add(edicionVehiculosPanel,BorderLayout.CENTER);
         f.setVisible(true);
         f.setExtendedState(f.getExtendedState() | JFrame.MAXIMIZED_BOTH);
         edicionVehiculosPanel.setPreferredSize(new Dimension(200,200));
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Concesionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Concesionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Concesionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Concesionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("Iniciando Concesionaria");
                new Concesionaria().setVisible(true);
            }
        });
    }

    /**
     * Ejecuta el frame de edicion a partir de la obtencion del vehiculo.
     * 
     * @param vehiculoId 
     */
    public void openEditVehiculo(Long vehiculoId){
        this.loadTable();
          
        if (this.previoEdicionVehiculosPanel != null) 
           this.frameEdit.remove(this.previoEdicionVehiculosPanel);
          
        EdicionVehiculosPanel edicionVehiculosPanel = new EdicionVehiculosPanel(vehiculoId,this.frameEdit, this);
        
         this.frameEdit.add(edicionVehiculosPanel,BorderLayout.CENTER);
         this.frameEdit.setVisible(true);
         this.frameEdit.setExtendedState(this.frameEdit.getExtendedState() | JFrame.MAXIMIZED_BOTH);
         edicionVehiculosPanel.setPreferredSize(new Dimension(200,200));
         this.frameEdit.setFocusable(true);
         this.previoEdicionVehiculosPanel = edicionVehiculosPanel;
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel3;
    private javax.swing.JTable vehiculosTable;
    // End of variables declaration//GEN-END:variables

    /**
     * Obtiene la tabla de vehiculos
     * 
     * @return JTable.
     */
    public JTable getVehiculosTable() {
        return vehiculosTable;
    }
}
